
name: meshx
description: Open-source Flutter plugin for offline Bluetooth mesh-like messaging (Bridgefy-style API). Stubs for native BLE; mock-friendly Dart API.
version: 0.1.0
homepage: https://example.com/meshx
repository: https://example.com/meshx
issue_tracker: https://example.com/meshx/issues
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.meshx
        pluginClass: MeshxPlugin
      ios:
        pluginClass: MeshxPlugin
